//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMyWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string topic { get; set; }
        public string message { get; set; }
        public string pcname { get; set; }
        public string lanip { get; set; }
        public string wanip { get; set; }
        public string macadress { get; set; }
    }
}
