//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMyWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mysiteEntities : DbContext
    {
        public mysiteEntities()
            : base("name=mysiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anasayfaSlider> anasayfaSlider { get; set; }
        public virtual DbSet<benkimim> benkimim { get; set; }
        public virtual DbSet<egitim> egitim { get; set; }
        public virtual DbSet<hizmetler> hizmetler { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<kisisel> kisisel { get; set; }
        public virtual DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual DbSet<tecrube> tecrube { get; set; }
        public virtual DbSet<yetenekler> yetenekler { get; set; }
        public virtual DbSet<KullaniciTurleri> KullaniciTurleri { get; set; }
        public virtual DbSet<BlogYazilari> BlogYazilari { get; set; }
    }
}
